// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Username": {
        "en": "Username",
        "de": "Nutzername",
        "ru": "имя пользователя",
        "pt": "Nome de usuário",
        "nl": "Gebruikersnaam",
        "fr": "Nom d'utilisateur",
        "it": "Nome utente",
        "es": "Nombre de usuario",
        "pl": "Nazwa Użytkownika"
    },
    "Password": {
        "en": "Password",
        "de": "Passwort",
        "ru": "пароль",
        "pt": "Senha",
        "nl": "Wachtwoord",
        "fr": "Mot de passe",
        "it": "Parola d'ordine",
        "es": "Contraseña",
        "pl": "Hasło"
    }
};